# Default values for pin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: registry.gitlab.com/aki237/pin
  tag: latest
  pullPolicy: IfNotPresent

pinSecret: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 9090

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
